### ISSUE TITLE
Save KB!

### ISSUE THREAD

**Issue by nandor690** [lechium/appletv-private-headers#1]
Fuck Twitter! I’ve been wondering why I haven’t seen you. Then realized they banned you! Probably not the best place but this was the only way I knew to contact you lol

**Comment by jpstar12** [comment]
Well in the spirit of “probably not the best place”- I’m using a much appreciated checkra1n jailbreak on the Apple TV 4th. nitoTV repo seems to have gotten rid of Kodi version that aren’t the Matrix 19 stuff? I’ve had the krypton 17.6 for the past year and has worked great. Today my version Kodi 17.6, from nito, re-downloaded as A Matrix version. The kodi i has disappeared and the new one replaced it with no way to downgrade or download a different older version. Needless to say no addons are available for the matrix v.19 Kodi so curious if an older version of Kodi that still uses current addons will come back? Thanks for any info or any time!

**Comment by lechium** [comment]
i trashed all my old builds, and they dont appear to host any of the old ones anymore. nothing i can or honestly will do to help.

**Comment by jpstar12** [comment]
Well dang. I enjoyed that Kodi app. That’s the whole reason I jailbroke the Apple TV. Thanks for the past year of news and movies while I had it.

**Comment by lechium** [comment]
@jpstar12 sorry, its just become an insane hassle to manage anything related to kodi. its insanely massive and i used to have to repackage and upload the old builds to fix various mistakes and then hope my isp cooperates to upload massive files each time. every single time i update it or do anything i get nothing but headaches because nothing works anymore, theres a reason ive never been a fan of kodi.

**Comment by lechium** [comment]
@jpstar12 i changed my mind because i found an old copy that i apparently didnt delete. you can now downgrade to the last 17 based version of kodi that i hosted before i cleared them out

**Comment by jpstar12** [comment]
@lechium Man, thanks a ton! I really appreciate you taking the time to put that back up there.
